<a href="./form">Add User</a>
<table border="1" class="table table-striped" style="margin-top:30px;">
        <thead class="bg-secondary text-white">
            <tr>
                <th>Id</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Mobile</th>
                <th>Status</th>
                <th>Created Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>  
            <?php foreach($this->getUserData() as $user):?>
                <tr>
                    <td><?= $user->getId(); ?></td>
                    <td><?= $user->getFirstName(); ?></td>
                    <td><?= $user->getLastName(); ?></td>
                    <td><?= $user->getEmail(); ?></td>
                    <td><?= $user->getMobile(); ?></td>
                    <td><?= $user->getStatus(); ?></td>
                    <td><?= $user->getCreatedDate(); ?></td>
                    <td><button onclick=""<?php echo $this->getUrl('*/*/Update');?>"">Update</button><br><button>Delete</button></td>
                </tr>
            <?php endforeach ?>
        </tbody>
</table>
