<?php $data = $this->getOrder()->getCustomer(); ?>
<div id="order-form_account">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head fieldset-legend head-account">Account Information</h4>
        </div>
        <div id="customer_account_fieds">
            <div class="fieldset " id="main">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                        <tbody>
                            <tr>
                                <td class="label"><label>Name<span class="required">*</span></label>
                                </td>
                                <td class="value">
                                    <input value="<?php echo $data->getFirstname().' '.$data->getLastname(); ?>" type="text" readonly>
                                </td>
                            </tr>
                            <tr>
                                <td class="label"><label>Email</label></td>
                                <td class="value">
                                    <input value="<?php echo $data->getEmail(); ?>" type="text" readonly>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>