<?php 
$grandTotal = $this->getOrder()->getTotal();
$shippingAmount = $this->getOrder()->getShippingAmount();
$total = $grandTotal-$shippingAmount;

?>
<div class="box-left entry-edit">
            <div class="entry-edit-head"><h4>Order Totals</h4></div>
            <div id="order-totals" class="order-totals"><div>
    <table cellspacing="0" cellpadding="8" width="100%">
        <tbody>
            <tr>
                <td class="a-right" colspan="1">Subtotal</td>
                <td  class="a-right"><span class="price"><?php echo '₹'.$total; ?></span></td>
            </tr>
            <tr>
                <td class="a-right" colspan="1">Shipping Charges</td>
                <td  class="a-right"><span class="price"><?php echo '₹'.$shippingAmount ?></span></td>
            </tr>
            <tr>
                <td  class="a-right" colspan="1"><strong>Grand Total</strong></td>
                <td  class="a-right"><strong><span class="price"><?php echo '₹'.$grandTotal; ?></span></strong></td>
            </tr>
        </tbody>
    </table>
</div>
