<?php $order = $this->getOrder(); ?>
<div class="content-header">
        <div id="order-header">
            <h3 class="icon-head head-sales-order">Order Details</h3>
        </div>
        <div class="form-buttons">

            <a href="<?php echo $this->getUrl('order/adminhtml_order/index'); ?>">
            <button type="button" class="scalable back"><span>Back</span></button></a>
            </div>

    </div>

    <?php echo $this->getChild('account')->setOrder($order)->toHtml(); ?>
         
    <?php echo $this->getChild('orderitems')->setOrder($order)->toHtml(); ?>

    <?php echo $this->getChild('billingaddress')->setOrder($order)->toHtml(); ?>
        
    <?php echo $this->getChild('shippingaddress')->setOrder($order)->toHtml() ?>
       
    <?php echo $this->getChild('payment')->setOrder($order)->toHtml(); ?>

    <?php echo $this->getChild('shipment')->setOrder($order)->toHtml(); ?>

    <?php echo $this->getChild('ordertotal')->setOrder($order)->toHtml(); ?>
   
</form>