    <ul class="tabs-horiz">
        <?php foreach($this->getTabs() as $key=>$tab):?>
            <li><a href="javascript:void(0)" onclick="object.setUrl('<?= $tab['url'];?>').load()" class="button"><?php echo $tab['label']; ?></a></li>
        <?php endforeach; ?>
    </ul>
  

<div id="contentHtml">
    <?= $this->getDefaultTabContent(); ?>
</div>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<script type="text/javascript">
    object = new Base();
    var $j = jQuery.noConflict();
</script>