<?php $billingAddress = $this->getBillingAddress()->getData(); ?>

<div id="order-addresses">
    <form id="billingAddressForm" method="post"
        action="<?php echo $this->getUrl('order/adminhtml_order_cart/saveBillingAddress'); ?>">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div id="order-billing_address" class="box-left">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head fieldset-legend head-billing-address">Billing Address</h4>
                    <div class="form-buttons"><input type="submit" class="scalable add" value="Save"></div>
                </div>

                <fieldset class="np">
                    <div class="order-address" id="order-billing_address_fields">
                        <div class="content">
                            <div class="hor-scroll">
                                <table cellspacing="0" class="form-list">
                                    <tbody>
                                        <tr>
                                            <td class="label"><label>Street<span class="required">*</span></label></td>
                                            <td class="value">
                                                <div><input name="billing[street]"
                                                    value="<?php echo $billingAddress['street']; ?>"
                                                    class=" input-text required-entry" type="text">
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label>Zip Code<span class="required">*</span></label></td>
                                            <td class="value">
                                                <input name="billing[postcode]"
                                                    value="<?php echo $billingAddress['postcode']; ?>"
                                                    class=" required-entry input-text required-entry" type="text">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label>State<span class="required">*</span></label></td>
                                            <td class="value">
                                                <input name="billing[region]"
                                                    value="<?php echo $billingAddress['region']; ?>"
                                                    class=" required-entry input-text required-entry" type="text">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label>City <span class="required">*</span></label></td>
                                            <td class="value">
                                                <input name="billing[city]" value="<?php echo $billingAddress['city']; ?>"
                                                    class=" required-entry input-text required-entry" type="text">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label>Country<span class="required">*</span></label>
                                            </td>
                                            <td class="value">
                                                <input name="billing[country_id]"
                                                    value="<?php echo $billingAddress['country_id']; ?>"
                                                    class="required-entry input-text" type="text">
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="order-save-in-address-book">
                            <input type="checkbox" name="saveBillingAddress" >
                            <label>Save in address book</label>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </form>