<?php $data = $this->getCart()->getCustomer(); ?>
<div id="order-form_account">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head fieldset-legend head-account">Account Information</h4>
        </div>
        <div id="customer_account_fieds">
            <div class="fieldset " id="main">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                        <tbody>
                            <tr>
                                <td class="label"><label>Name<span class="required">*</span></label>
                                </td>
                                <td class="value">
                                    <input id="name" name="order[account][name]"
                                        value="<?php echo $data->getFirstname().' '.$data->getLastname(); ?>"
                                        class=" validate-email input-text" type="text">
                                </td>
                            </tr>
                            <tr>
                                <td class="label"><label for="email">Email</label></td>
                                <td class="value">
                                    <input id="email" name="order[account][email]" value=<?php echo $data->getEmail(); ?>
                                        class="validate-email input-text" type="text">
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>