<?php $cart = $this->getCart(); ?>
<form action="" method="POST" id="cartForm">
    <?php echo $this->getBlockHtml('formkey'); ?>  

    <?php echo $this->getChild('account')->setCart($cart)->toHtml() ?>
         
    <?php echo $this->getLayout()->createBlock('order/adminhtml_order_cart_product')->toHtml() ?>

    <?php echo $this->getChild('cartitems')->setCart($cart)->toHtml() ?>

	<?php echo $this->getLayout()->createBlock('order/adminhtml_order_cart_billingaddress')->toHtml() ?>
        
    <?php echo $this->getLayout()->createBlock('order/adminhtml_order_cart_shippingaddress')->toHtml() ?>
       
    <?php echo $this->getLayout()->createBlock('order/adminhtml_order_cart_payment')->toHtml() ?>

    <?php echo $this->getLayout()->createBlock('order/adminhtml_order_cart_shipment')->toHtml() ?>
   
</form>