<?php $shippingAddress = $this->getShippingAddress()->getData(); ?>

<form id="shippingAddressForm" method="post"
    action="<?php echo $this->getUrl('order/adminhtml_order_cart/saveShippingAddress'); ?>">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div id="order-shipping_address" class="box-right">
        <div class="entry-edit" style="position: relative;">
            <div class="entry-edit-head">
                <h4 class="icon-head fieldset-legend head-shipping-address">Shipping Address</h4>
                <div class="form-buttons"><input type="submit" class="scalable add" value="Save"></div>
            </div>
            <fieldset class="np">
                <div class="order-save-in-address-book">
                    <input name="sameAsBilling" type="checkbox">
                    <label>Same As Billing Address</label>

                    <input name="saveShippingAddress" type="checkbox">
                    <label>Save in address book</label>
                </div>

                <div class="order-address" id="order-shipping_address_fields">
                    <div class="content">
                        <div class="hor-scroll">
                            <table cellspacing="0" class="form-list">
                                <tbody>
                                    <tr>
                                        <td class="label"><label>Street<span class="required">*</span></label></td>
                                        <td class="value">
                                            <div><input name="shipping[street] value="<?php echo $shippingAddress['street']; ?>"
                                                    class="input-text required-entry" type="text">
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label>Zip Code<span class="required">*</span></label></td>
                                        <td class="value">
                                            <input name="shipping[postcode]"
                                                value="<?php echo $shippingAddress['postcode']; ?>"
                                                class=" required-entry input-text required-entry" type="text">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label>City <span class="required">*</span></label></td>
                                        <td class="value">
                                            <input name="shipping[city]" value="<?php echo $shippingAddress['city']; ?>"
                                                class=" required-entry input-text required-entry" type="text">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label>State <span class="required">*</span></label></td>
                                        <td class="value">
                                            <input name="shipping[region]" value="<?php echo $shippingAddress['region']; ?>"
                                                class=" required-entry input-text required-entry" type="text">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label>Country<span class="required">*</span></label>
                                        </td>
                                        <td class="value">
                                            <input name="shipping[country_id]"
                                                value="<?php echo $shippingAddress['country_id']; ?>"
                                                class="required-entry input-text" type="text">
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </fieldset>
        </div>
    </div>
</form>
</div>